[supervisord]
user=root
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:media]
user=dvorcam
command=/usr/local/bin/mediamtx /data/runtime/mediamtx.yml
priority=10
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=25
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:worker]
user=dvorcam
command=python /app/worker.py
priority=20
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=150
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:web]
user=dvorcam
command=gunicorn --bind 0.0.0.0:9001 --workers 1 --threads 8 --timeout 120 --error-logfile - web:app
priority=30
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
